# Generated by Django 5.2.9 on 2025-12-08 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Telefone/WhatsApp')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Aniversário')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição Detalhada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('size', models.CharField(blank=True, max_length=10, verbose_name='Tamanho (P, M, G, etc.)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/Referência Interna')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo para Venda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Venda Fechada (Finalizada)')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de Pagamento')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário na Venda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
