# Generated by Django 5.2.9 on 2025-12-09 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_alter_sale_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem Principal'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery/', verbose_name='Foto da Galeria')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Foto de Capa (Opcional)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Produto Relacionado')),
            ],
            options={
                'verbose_name': 'Foto Adicional',
                'verbose_name_plural': 'Galeria de Fotos',
            },
        ),
    ]
