# Generated by Django 5.2.9 on 2025-12-09 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('LATE', 'Atrasado')], default='PENDING', max_length=10, verbose_name='Status de Pagamento')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('LATE', 'Atrasado')], default='PENDING', max_length=10, verbose_name='Status de Pagamento')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer', verbose_name='Cliente da Fatura')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='store.sale', verbose_name='Venda Relacionada')),
            ],
            options={
                'verbose_name': 'Fatura (Conta a Receber)',
                'verbose_name_plural': 'Faturas (Contas a Receber)',
            },
        ),
    ]
